name: "Benchmark"

on:
  push:
    branches: [ main, version-* ]
    paths:
      - 'include/**'
      - 'benchmark/**'
      - '.github/workflows/benchmark.yml'
  pull_request:
    branches: [ main, version-* ]
    types: [ opened, synchronize, reopened ]
    paths:
      - 'include/**'
      - 'benchmark/**'
      - '.github/workflows/benchmark.yml'
  workflow_dispatch:

jobs:
  # Ubuntu check
  benchmark-on-ubuntu:
    if: github.repository_owner == 'Kim-J-Smith'
    runs-on: ubuntu-26.04

    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v6

      # Install cmake and compilers
      - name: Install compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
          sudo apt-get install -y g++-16 clang
          sudo apt-get install python3

      # Config CMake for compilers
      - name: Config CMake
        working-directory: benchmark
        run: |
          cmake -B build -S . \
            -DCMAKE_CXX_STANDARD=23 \
            -DCMAKE_C_COMPILER=gcc-16 \
            -DCMAKE_CXX_COMPILER=g++-16

      # Run benchmark
      - name: Run benchmark with C++
        working-directory: benchmark
        run: |
          cmake --build build --config Release --target benchmark --parallel
          cd ./compiletime
          chmod a+x ./run_benchmark.sh
          ./run_benchmark.sh
          cd ..
          mkdir -p runtime
          mv build/runtime-report.md runtime/gcc-runtime-report.md

      # Output the report
      - name: Save the benchmark result
        uses: actions/upload-artifact@v7
        with:
          name: benchmark-ubuntu-gcc-reports
          path: |
            benchmark/runtime/gcc-runtime-report.md
            benchmark/compiletime/benchmark_report.md
          retention-days: 60


  # Windows check
  benchmark-on-windows:
    if: github.repository_owner == 'Kim-J-Smith'
    runs-on: windows-2025-vs2026

    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v6

      # Config CMake for compilers
      - name: Config CMake
        working-directory: benchmark
        shell: bash
        run: |
          cmake -B build -S . \
            -G "Visual Studio 18 2026" \
            -A x64 \
            -DCMAKE_CXX_STANDARD=23

      # Run benchmark
      - name: Run benchmark with C++
        working-directory: benchmark
        shell: bash
        run: |
          cmake --build build --config Release --target benchmark --parallel
          mkdir -p runtime
          mv build/runtime-report.md runtime/msvc-runtime-report.md

      # Output the report
      - name: Save the benchmark result
        uses: actions/upload-artifact@v7
        with:
          name: benchmark-windows-vs2026-reports
          path: |
            benchmark/runtime/msvc-runtime-report.md
          retention-days: 60
