name: "Test"

on:
  push:
    branches: [ main, version-* ]
  pull_request:
    branches: [ main, version-* ]
    types: [ opened, synchronize, reopened ]

jobs:
  # Ubuntu check
  test-on-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpp_standards: [11, 14, 17, 20, 23]
        compiler: [
          { name: "GCC-13", cc: "gcc-13", cxx: "g++-13", pkg: "g++-13" },
          { name: "GCC-14", cc: "gcc-14", cxx: "g++-14", pkg: "g++-14" },
          { name: "Clang-18", cc: "clang-18", cxx: "clang++-18", pkg: "clang-18" },
          { name: "Clang-19", cc: "clang-19", cxx: "clang++-19", pkg: "clang-19" },
        ]
      fail-fast: false

    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v6

      # Install cmake and compilers
      - name: Install compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build
          sudo apt-get install -y ${{ matrix.compiler.pkg }}

      # Config CMake for compilers
      - name: Config with C++${{ matrix.cpp_standards }}
        working-directory: test
        run: |
          cmake -B build -S . \
            -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standards }} \
            -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}

      # Run tests
      - name: Run tests with C++${{ matrix.cpp_standards }}
        working-directory: test
        run: cmake --build build --config Debug --target test

  # Windows check
  test-on-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        cpp_standards: [14, 17, 20, 23]
        arch: [x64]
        toolset: [v143]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          toolset: ${{ matrix.toolset }}

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Config with C++${{ matrix.cpp_standards }}
        working-directory: test
        shell: bash
        run: |
          cmake -B build -S . \
            -G "Visual Studio 17 2022" \
            -A ${{ matrix.arch }} \
            -T ${{ matrix.toolset }} \
            -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standards }}

      - name: Build and test
        working-directory: test
        run: cmake --build build --config Debug --target test
