name: "Test"

on:
  push:
    branches: [ main, version-* ]
  pull_request:
    branches: [ main, version-* ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  # GCC 13
  ubuntu-gcc-13:
    if: github.repository_owner == 'Kim-J-Smith'
    runs-on: ubuntu-latest

    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v6

      # Run GCC tests
      - name: Run GCC tests
        working-directory: test
        shell: bash
        run: |
          bash ./script/test-gcc.sh 13

  # GCC 14
  ubuntu-gcc-14:
    if: github.repository_owner == 'Kim-J-Smith'
    runs-on: ubuntu-latest

    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v6

      # Run GCC tests
      - name: Run GCC tests
        working-directory: test
        shell: bash
        run: |
          bash ./script/test-gcc.sh 14

  # Clang 18
  ubuntu-clang-18:
    if: github.repository_owner == 'Kim-J-Smith'
    runs-on: ubuntu-latest

    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v6

      # Run Clang tests
      - name: Run Clang tests
        working-directory: test
        shell: bash
        run: |
          bash ./script/test-clang.sh 18

  # Clang 19
  ubuntu-clang-19:
    if: github.repository_owner == 'Kim-J-Smith'
    runs-on: ubuntu-latest

    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v6

      # Run Clang tests
      - name: Run Clang tests
        working-directory: test
        shell: bash
        run: |
          bash ./script/test-clang.sh 19

  # VS 2022
  windows-vs-2022:
    if: github.repository_owner == 'Kim-J-Smith'
    runs-on: windows-2022

    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v6

      # Run MSVC tests
      - name: Run MSVC tests
        working-directory: test
        shell: bash
        run: |
          bash ./script/test-msvc.sh "Visual Studio 17 2022"

  # VS 2026
  windows-vs-2026:
    if: github.repository_owner == 'Kim-J-Smith'
    runs-on: windows-2025-vs2026

    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v6

      # Run MSVC tests
      - name: Run MSVC tests
        working-directory: test
        shell: bash
        run: |
          bash ./script/test-msvc.sh "Visual Studio 18 2026"
